data={
    "p1":{
        "name":"Jhom",
        "username":"kevler",                           #datas
        "email":"jhom@gmail.com",
        "password":"jhon123"
    },
    "p2":{
        "name":"Josh",
        "username":"David",
        "email":"jhos@gmail.com",
        "password":"jhos123"
    },
    "p3":{
        "name":"Poms",
        "username":"Dunk",
        "email":"poms@gmail.com",
        "password":"poms123"
    },
    "p4":{
        "name":"Patrick",
        "username":"kevler1",
        "email":"patrick@gmail.com",
        "password":"patrick123"
    } 
}